[package]
name = "sqlite_connect"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "*", features = ["attributes"] }
futures = "*"
sqlx = { version = "0.8.2", features = [
  "runtime-async-std-native-tls",
  "sqlite",
] }
