[package]
name = "async_await"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "*", features = ["blocking", "json"] }
error-chain = "*"
tokio = { version = "*", features = ["full"] }
