[package]
name = "pastebin_clone"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3.0"
rusqlite = "0.25"
rand = "0.8"
actix-files = "0.5"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "*", features = ["blocking"] }
